### ISSUE TITLE
possibility of race condition in commit mode?

### ISSUE THREAD

**Issue by pdeva** [mbrobbel/rustfmt-check#1004]
can this action run in this race condition when in `commit` mode?:

1.  commit A is pushed in a PR
2. `rustfmt-check` is running and detects it needs to push a commit with formatted rust code and pushes commit B.
3. meanwhile user pushed commit C with new code.
4. commit B from `rustfmt-check` arrives later than commit C, and this commit B ends up overwriting commit C.

**Comment by mbrobbel** [comment]
`B` from the `rustfmt-check` would be rejected if it's pushed after `C`.

We would have to explicitly set [`force`](https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#update-a-reference--parameters) with `updateRef` to overwrite.
