### ISSUE TITLE
##[error]Cannot read property 'payload' of undefined

### ISSUE THREAD

**Issue by steffenix** [mbrobbel/rustfmt-check#210]
I am using the configuration from the example. I think the update to github action 4 something broke.

```
 Run mbrobbel/rustfmt-check@master
0s
    CARGO_TERM_COLOR: always
Run mbrobbel/rustfmt-check@master
  with:
    token: ***
  env:
    CARGO_TERM_COLOR: always
##[error]Cannot read property 'payload' of undefined

```

https://github.com/nash-io/openlimits/runs/967287004

**Comment by mbrobbel** [comment]
Sorry about that. I was using the wrong context after updating the @actions/github package. I just pushed a fix and tested it with the example PRs.
