### ISSUE TITLE
Error rustup component add rustfmt

### ISSUE THREAD

**Issue by kehiy** [mbrobbel/rustfmt-check#850]
I'm trying to use this action
but I got this:
```
error: 'cargo-fmt' is not installed for the toolchain 'nightly-x86_64-unknown-linux-gnu'
To install, run `rustup component add rustfmt`
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 1
```

ERROR link:
https://github.com/zurvan-lab/redvin/actions/runs/6410479774/job/17403865191?pr=7

**Comment by kehiy** [comment]
@mbrobbel can you help me?

**Comment by mbrobbel** [comment]
You need to add `rustfmt` to the `components` argument of the `rust-toolchain` action.

I'll update the instructions in the README tomorrow.

**Comment by kehiy** [comment]
@mbrobbel Hi, thanks
I'm waiting for your update...
