### ISSUE TITLE
Check mode (live up to the name)

### ISSUE THREAD

**Issue by alerque** [mbrobbel/rustfmt-check#92]
I would be interested in using an action that actually ran a check as a PR review. I see this is on your agenda:

> * Add review with suggestions.
> * Check mode to fail the job if formatting is required.

...but right now the project seems to do something that is different than the name. I don't want it to change things and push commits, I want it to check PRs. Given the name of the project I figure this is fair to track in an issue ;-)

**Comment by mbrobbel** [comment]
I'll start working on those other output modes 👍
