### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'path/to/file.rs'

### ISSUE THREAD

**Issue by ItsSunnyMonster** [mbrobbel/rustfmt-check#921]
This error only shows up for two files in my repository. When I ran rustfmt locally and committed, this error was no longer there.

**Comment by mbrobbel** [comment]
Do you have a link to the failed job or a log?

**Comment by ItsSunnyMonster** [comment]
Here is the link to one of the failed jobs: [https://github.com/ItsSunnyMonster/ruxel/actions/runs/7282879844/job/19845943496](https://github.com/ItsSunnyMonster/ruxel/actions/runs/7282879844/job/19845943496)

It is interesting because this error has never come up again even when I tried purposefully messing up the formatting for the same file. When I did that, the action ran correctly and made a commit which formatted the file correctly.

**Comment by mbrobbel** [comment]
It seems it's not splitting output lines correctly. I'll attempt to provide a fix. Thanks for reporting this.
